#!/bin/bash
# tail -n +2 skips the first line
# tr -s " " replaces every instance of multiple spaces with a single space (tr -d " " would just delete all spaces)
# Last cut removes everything beyond the second space
tail -n +2 | cut -f1 | sort | uniq -c | sort -nr | head -n 11 | tr -s " " | cut -d " " -f3
