#!/usr/bin/env bash
# This script provides information about the 'school'
filename="./school"

if [ -e "$filename" ]
then
    echo  "school file exists"
elif [ -s "$filename" ]
then
    echo "schoolfile is not empty"
elif [ ! -s "$filename" ]
then
    echo "school file is empty"
else
    echo "school file does not exist"
fi

if [ -f "$filename" ]
then
    echo "school is a regular file"
fi
