#!/usr/bin/env bash
# This script is displaying 'Best School' ten times using a while loop
# shellcheck disable=SC2004
# while (( alternative requires <= terminology
i=1
while  [ $i -le 10 ]
do
    echo "Best School"
    i=$(($i + 1))
done
