#!/usr/bin/env bash
# This script is displaying 'bad luck for the 4th iteration, 'good luck for the 8th iteration, and 'Best School' otherwise for ten loops.
i=0
while [ $i -le 9 ]
do
i=$((i + 1))
 if [ $i = 4 ]
then
    echo "bad luck"
elif [ $i = 8 ]
then
    echo "good luck"
 else
     echo "Best School"
 fi
done
