#!/usr/bin/env bash
# This script is displaying '4' and 'bad luck from China' for the 4th iteration, '9' and 'bad luck from Japan' for the 9th iteration, '17' and 'bad luck from Italy' for the 17th iteration, and numbers one to 20 otherwise.   
i=0
while [ $i -le 19 ]
do
i=$((i + 1))
case $i in
    4)
	echo -e "4\nbad luck from China"
	;;
    9)
	echo -e "9\nbad luck from Japan"
	;;
    17)
	echo -e "17\nbad luck from Italy"
	;;
    *)
	echo $i
	;;
esac
done
