#!/usr/bin/env bash
# This script is displaying '4' and 'bad luck from China' for the 4th iteration, '9' and 'bad luck from Japan' for the 9th iteration, '17' and 'bad luck from Italy' for the 17th iteration, and numbers one to 20 otherwise.   
i=1
while [ $i -le 20 ]
do
    echo $i
i=$((i + 1))
case $i in
    4)
	echo "4 bad luck from China"
	;;
    9)
	echo "9 bad luck from Japan"
	;;
    17)
	echo "17 bad luck from Italy"
esac
done
