#!/usr/bin/env bash
# This script prints a twelve-hour clock. Every 60th minute, 'Hour: x' is displayed for each hour.
i=0
j=1

while [ $i -le 12 ]
do
    echo "Hour: $i"
    while [ $j -lt 60 ]
    do
	echo $j
	j=$((j + 1))
    done
    i=$((i + 1))
done
