#!/usr/bin/env bash
# This script prints a twelve-hour clock. Every 60th minute, 'Hour: x' is displayed for each hour.
i=0
echo "Hour: 0"
while [ $i -le 12 ]; do
    seq  59
    i=$((i + 1))
    case $i in
	1)
	    echo "Hour: 1"
	    ;;
	2)
	    echo "Hour: 2"
	    ;;
	3)
	echo "Hour: 3"
	;;
	4)
	echo "Hour: 4"
	;;
	5)
	    echo "Hour: 5"
	    ;;
	6)
	    echo "Hour: 6"
	    ;;
	7)
	    echo "Hour: 7"
	    ;;
	8)
	    echo "Hour: 8"
	    ;;
	9)
	    echo "Hour: 9"
	    ;;
	10)
	    echo "Hour: 10"
	    ;;
	11)
	    echo "Hour: 11"
	    ;;
	12)
	    echo "Hour: 12"
	    ;;
    esac
    done
