#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data (referring to Apache log file).
# 'sort' gets duplicate entries next to each other; 'uniq' shows the sequential frequency of each entry; 'sort' again orders this frequency 

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr 
