#!/usr/bin/env bash
# This script provides information about the 'school'
filename="./school"

if [ ! -e "$filename" ]
then
    echo  "school file does not exist"
elif [ -s "$filename" ]
then
    echo -e "school file exists\nschool file is not empty"
elif [ ! -s "$filename" ]
then
    echo -e "school file exists\nschool file is empty"
else
    echo "school file does exist"
fi

if [ -f "$filename" ]
then
    echo "school is a regular file"
fi
