#!/usr/bin/env bash
# This script repeats 'To infinity and beyond' indefinitely with a sleep 2 between each iteration.
# Creates /var/run/myscript.pid containing its PID.
# Displays 'I hate the kill command' when receiving a SIGTERM signal.
# Displays 'Y U no love me?!' when receiving a SIGINT signal.
# Deletes /var/run/myscript.pid and terminates itself when receiving a SIGTERM or SIGQUIT signal.

echo $$ >/var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
