#!/usr/bin/env bash
# This script repeats 'To infinity and beyond' indefinitely with a sleep 2 between each iteration, and prints 'I am invincible!!!' after receiving a SIGTERM signal

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
